services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: wuejejejAURA777
    volumes:
      - ./sql_data:/var/opt/mssql/data
    networks:
      - app-network

  # New service for Adminer
  adminer:
    image: adminer:latest # Or specify a version like adminer:4.8.1
    ports:
      - "8080:8080" # Access via http://localhost:8080
    depends_on:
      - sqlserver
    networks:
      - app-network
volumes:
  sql_data:

networks:
  app-network:
    driver: bridge