version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SQL_SERVER_PASSWORD}
    volumes:
      - sql_data:/var/opt/mssql/data

volumes:
  sql_data: